name: deploy
on:
    push:
     branches: main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: infra-deploy
        run: |
          sudo apt-get -y update; sudo apt-get -y install git
          git clone git@github.com:saipothereddy/main.git -b main
          ls -la
          cd main/
          git checkout -b test
          git pull --rebase origin test
          git push --set-upstream origin test
