name: deploy
on:
    push:
     branches: main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: infra-deploy
        run: |
          sudo apt-get -y update; sudo apt-get -y install git
          git clone git@github.com:saipothereddy/liquibase.git -b main
          ls -la
          cd liquibase/
          if: "!contains(git chest -b test1, 'SKIP SCRIPTS')"    <--- skips everything in this job if head commit message does not contain 'SKIP SCRIPTS'
          git push -u origin test1
