name: deploy
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: infra-deploy
        run: |
          sudo apt-get -y update; sudo apt-get -y install git
          git@github.com:saipothereddy/main.git -b master
          ls -la
          cd main/
          git checkout -b test
          git pull --rebase origin test
          git push --set-upstream origin test
